Working tournaments and categories with rspec
Kevindm14/Surf-tournament pull request #3
Opened 2018-12-04 16:08 UTC by Kevindm14

2018-12-04 17:37 UTC, lmsilvera requested changes

2018-12-04 17:37 UTC, lmsilvera commented on app/models/tournament.rb
> +  # validates :final_date, if: -> { :final_date > :start_date || require_validation}
por favor borra las cosas comentadas

2018-12-04 17:37 UTC, lmsilvera commented on config/routes.rb
> +    resources :tournament_categories
considero que no necesitamos esta ruta

2018-12-04 18:41 UTC, lmsilvera commented
- `/tournaments/new` cuando le doy `save`sin haber colocado algun dato se queda en la misma sin mostarme error o algun mensaje de validacion
- Al momento de crear un torneo me permite colocar una final date menor a initial date.

2018-12-04 21:22 UTC, lmsilvera requested changes

2018-12-04 21:22 UTC, lmsilvera commented on app/controllers/tournaments_controller.rb
> +    @tournament_category = TournamentCategory.all
esta variable la utilizas en la vista?

2018-12-04 21:22 UTC, lmsilvera commented on app/models/tournament.rb
> +    if start_date > final_date
y si son un solo día?

2018-12-04 21:22 UTC, lmsilvera commented on spec/models/tournament_spec.rb
> +end
haz los tests para validar start_date > final_date.

2018-12-04 22:34 UTC, Kevindm14 commented on app/controllers/tournaments_controller.rb
> +    @tournament_category = TournamentCategory.all
Ya la he quitado

2018-12-05 19:34 UTC, lmsilvera requested changes

2018-12-05 19:34 UTC, lmsilvera commented on spec/controllers/tournament_spec_controller.rb
> +    context "With valid attributes" do
¿que pasa si los datos no son correctos?

2018-12-05 19:34 UTC, lmsilvera commented on spec/controllers/tournament_spec_controller.rb
> +    context "With valid attributes" do
es decir, el caso de "invalid attributes".

2018-12-05 19:34 UTC, lmsilvera commented on spec/models/tournament_spec.rb
> +      expect(:start_date).to be > :final_date
podrias hacerle test tambien al caso en el que causa error

2018-12-05 19:34 UTC, lmsilvera commented on spec/controllers/tournament_spec_controller.rb
> +    before { patch :update, params: {id: create_tournament, tournament: attributes_for(:tournament)} }
por que haces este test si en el controlador no tienes un metodo update?

2018-12-05 19:34 UTC, lmsilvera commented on spec/factories/tournament.rb
> +    start_date { "Wed, 05 Dec 2018" }
por qué las fechas están fijas? y si corro los tests el día 6 de diciembre.

2018-12-05 19:37 UTC, lmsilvera commented
Si no puedo editar torneos, ¿por qué puedo crear torneos sin crearle categorias?

2018-12-06 16:28 UTC, lmsilvera approved these changes

2018-12-06 16:30 UTC, merged